// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Risk extends mvvm.proxies.Model
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Risk";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		INsuredName("INsuredName"),
		InceptionDate("InceptionDate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Risk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Risk"));
	}

	protected Risk(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject riskMendixObject)
	{
		super(context, riskMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Risk", riskMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Risk");
	}

	/**
	 * @deprecated Use 'Risk.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Risk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Risk.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Risk initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Risk(context, mendixObject);
	}

	public static myfirstmodule.proxies.Risk load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Risk.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Risk> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Risk> result = new java.util.ArrayList<myfirstmodule.proxies.Risk>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Risk" + xpathConstraint))
			result.add(myfirstmodule.proxies.Risk.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of INsuredName
	 */
	public final java.lang.String getINsuredName()
	{
		return getINsuredName(getContext());
	}

	/**
	 * @param context
	 * @return value of INsuredName
	 */
	public final java.lang.String getINsuredName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.INsuredName.toString());
	}

	/**
	 * Set value of INsuredName
	 * @param insuredname
	 */
	public final void setINsuredName(java.lang.String insuredname)
	{
		setINsuredName(getContext(), insuredname);
	}

	/**
	 * Set value of INsuredName
	 * @param context
	 * @param insuredname
	 */
	public final void setINsuredName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String insuredname)
	{
		getMendixObject().setValue(context, MemberNames.INsuredName.toString(), insuredname);
	}

	/**
	 * @return value of InceptionDate
	 */
	public final java.util.Date getInceptionDate()
	{
		return getInceptionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of InceptionDate
	 */
	public final java.util.Date getInceptionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.InceptionDate.toString());
	}

	/**
	 * Set value of InceptionDate
	 * @param inceptiondate
	 */
	public final void setInceptionDate(java.util.Date inceptiondate)
	{
		setInceptionDate(getContext(), inceptiondate);
	}

	/**
	 * Set value of InceptionDate
	 * @param context
	 * @param inceptiondate
	 */
	public final void setInceptionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date inceptiondate)
	{
		getMendixObject().setValue(context, MemberNames.InceptionDate.toString(), inceptiondate);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Risk that = (myfirstmodule.proxies.Risk) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Risk";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
