// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mvvm.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.ArrayList;
import java.util.HashMap;

public class GetViews extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __SourceModel;
	private mvvm.proxies.Model SourceModel;

	public GetViews(IContext context, IMendixObject SourceModel)
	{
		super(context);
		this.__SourceModel = SourceModel;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.SourceModel = __SourceModel == null ? null : mvvm.proxies.Model.initialize(getContext(), __SourceModel);

		// BEGIN USER CODE
		HashMap<String, String> views = InitializeViews.getViewsForModel(SourceModel);
		ArrayList<IMendixObject> updateViews = new ArrayList<IMendixObject>();

		for (String associationName : views.keySet()) {
			String objectName = views.get(associationName);
			IMendixObject view = InitializeViews.getView(getContext(), SourceModel, objectName, associationName).getObject();
			updateViews.add(view);
		}

		return updateViews;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetViews";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
