// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mvvm.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class LoadViews extends CustomJavaAction<java.lang.Boolean>
{
	private java.util.List<IMendixObject> __Views;
	private java.util.List<mvvm.proxies.View> Views;
	private IMendixObject __ModelParameter1;
	private mvvm.proxies.Model ModelParameter1;

	public LoadViews(IContext context, java.util.List<IMendixObject> Views, IMendixObject ModelParameter1)
	{
		super(context);
		this.__Views = Views;
		this.__ModelParameter1 = ModelParameter1;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.Views = new java.util.ArrayList<mvvm.proxies.View>();
		if (__Views != null)
			for (IMendixObject __ViewsElement : __Views)
				this.Views.add(mvvm.proxies.View.initialize(getContext(), __ViewsElement));

		this.ModelParameter1 = __ModelParameter1 == null ? null : mvvm.proxies.Model.initialize(getContext(), __ModelParameter1);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "LoadViews";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
